# Generated by Django 4.2.2 on 2023-06-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_to',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
