# Generated by Django 4.2.2 on 2023-06-22 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_related_to_alter_task_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
