# Generated by Django 4.2.2 on 2023-06-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='host',
        ),
    ]
