# Generated by Django 4.2.2 on 2023-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_user_task_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='related_to',
            field=models.CharField(max_length=25),
        ),
    ]
